/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "DatabaseUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ForgeVpc": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
    "SolforgeAiApiRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "SolforgeAiService": {
      "service": string
      "type": "sst.aws.Service"
      "url": string
    }
    "SolforgeSh": {
      "type": "sst.cloudflare.Worker"
      "url": string
    }
    "SolforgeWeb": {
      "type": "sst.aws.Astro"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}