/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransactionsIndexRouteImport } from './routes/transactions.index'
import { Route as TransactionsSignatureRouteImport } from './routes/transactions.$signature'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIndexRoute = TransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsSignatureRoute = TransactionsSignatureRouteImport.update({
  id: '/transactions/$signature',
  path: '/transactions/$signature',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/transactions/$signature': typeof TransactionsSignatureRoute
  '/transactions': typeof TransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/transactions/$signature': typeof TransactionsSignatureRoute
  '/transactions': typeof TransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/transactions/$signature': typeof TransactionsSignatureRoute
  '/transactions/': typeof TransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/transactions/$signature' | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/transactions/$signature' | '/transactions'
  id: '__root__' | '/' | '/transactions/$signature' | '/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TransactionsSignatureRoute: typeof TransactionsSignatureRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/': {
      id: '/transactions/'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/$signature': {
      id: '/transactions/$signature'
      path: '/transactions/$signature'
      fullPath: '/transactions/$signature'
      preLoaderRoute: typeof TransactionsSignatureRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TransactionsSignatureRoute: TransactionsSignatureRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
