/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/// <reference types="vite/client" />
interface ImportMetaEnv {
  readonly AI_API_URL: string
  readonly VITE_SOLANA_RPC_URL: string
}
interface ImportMeta {
  readonly env: ImportMetaEnv
}